# Generated by Django 2.2.5 on 2019-09-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0002_auto_20190925_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
