# Generated by Django 2.2.5 on 2019-09-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0003_auto_20190925_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birth',
            name='username',
        ),
        migrations.AddField(
            model_name='birth',
            name='user',
            field=models.CharField(default='some', max_length=30),
        ),
    ]
