# Generated by Django 2.2.5 on 2019-09-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0004_auto_20190925_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
