# Generated by Django 2.2.5 on 2019-09-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0005_auto_20190925_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
