# Generated by Django 2.2.5 on 2019-09-25 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0007_auto_20190925_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be startwith 6,7,8,9 'and length should be 10 digits allowed.", regex='^[6-9]\\d{9}$')]),
        ),
    ]
