# Generated by Django 2.2.5 on 2019-09-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0008_birth_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='birthday',
            field=models.DateTimeField(blank=True, default='YY-MM-DD', null=True),
        ),
    ]
