# Generated by Django 2.2.5 on 2019-09-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0009_auto_20190926_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='birthday',
            field=models.DateTimeField(blank=True, default='yy-mm-dd (2019-09-29)', null=True),
        ),
    ]
