# Generated by Django 2.2.5 on 2019-09-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0010_auto_20190926_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='birth',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='birth',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
